Repository Kittycat58/curly-system, pull requests merged in 2023-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#2 Update README.md
  README.md
Labels: hacktoberfest-accepted

#3 Added Contributing.md
  Contributing.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#4 Update treasure hunt.py
  Basic level/treasure hunt.py
Labels: enhancement, hacktoberfest-accepted

#6 Update README.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#8 fix: Update README.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#10 home added
  Basic level/home.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#11 fix: Update README.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#14 feat: Added one python game for stone, paper, scissors
  Rock-Paper-Scissors.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#15 Added eval keyword
  Basic level/calculator/main.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#16 Add Script to merge subfolder contents into a main folder
  Basic level/merge_folders.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#19 Added MIT License
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted
